config/routes.rb
# TitanControl::Engine.routes.draw do
# end

Rails.application.routes.draw do
  devise_for :users, :class_name => "TitanControl::User", :path_prefix => 'admin', :controllers => { :sessions => "admin/sessions", :passwords => "admin/passwords" }

  namespace :admin do
    get '/' => 'dashboard#index', :as => :dashboard
    resources :categories, :except => [:show]
    resources :cms_blocks, :except => [:show]
    resources :cms_pages, :except => [:show]
  end

  # CMS Dynamic Routes
  TitanControl::CmsMeta.all.each do |cms|
    if cms.metaable.is_showable
      extension = File.extname(cms.url).sub(/^\./, '')

      path = "#{cms.url}"
      options = {:as => "cms_#{cms.id}", :id => cms.id}
      if extension.empty?
        path << "(.:format)"
      else
        options.merge!({:format => false, :defaults => {:format => extension}})
      end
      get({path => 'cms#show'}.merge(options))
    end
  end if TitanControl::CmsMeta.table_exists?

  root :to => 'cms#show'
end

app/models/titan_control/cms_page.rb
module TitanControl
  class CmsPage < ActiveRecord::Base
    include TitanControl::ModelCommonality::Metaable
    include TitanControl::ModelCommonality::RouteReload

    STATUSES = ['draft','published']

    has_many :cms_page_categories, :dependent => :destroy
    has_many :categories, :through => :cms_page_categories
    has_many :cms_page_cms_blocks, :dependent => :destroy
    has_many :cms_blocks, :through => :cms_page_cms_blocks

    scope :active_menu, where("menu_title IS NOT NULL").order('sort ASC')
    scope :published, where(:status => 'published')

    validates :status, :inclusion => {:in => STATUSES}

    def is_showable
      return self.status == 'published'
    end

  end
end

app/controllers/admin/cms_pages_controller.rb
class Admin::CmsPagesController < Admin::BaseController
  before_filter :load_cms_page, :only => [:edit, :update, :destroy]

  def index
    @cms_pages = TitanControl::CmsPage.meta_title_order
  end

  def new
    @cms_page = TitanControl::CmsPage.new
    @cms_page.build_cms_meta
    1.times { @cms_page.cms_meta.cms_contents.build }
  end

  def create
    @cms_page = TitanControl::CmsPage.new(params[:cms_page])
    if @cms_page.save
      redirect_to((params[:commit] == 'Save and Continue Edit' ? edit_cms_page_url(@cms_page) : cms_pages_url), :notice => 'Page was successfully created.')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cms_page.update_attributes(params[:cms_page])
      redirect_to((params[:commit] == 'Save and Continue Edit' ? edit_cms_page_url(@cms_page) : cms_pages_url), :notice => 'Page was successfully updated.')
    else
      render :edit
    end
  end

  def destroy
    @cms_page.destroy
    redirect_to(cms_pages_url, :notice => 'Page was deleted.')
  end

  protected

  def load_cms_page
    @cms_page = TitanControl::CmsPage.find(params[:id])
  end

end

app/helpers/admin/cms_pages_helper.rb
module Admin::CmsPagesHelper
end

app/views/admin/cms_pages/_form.html.erb
<%= form_for [:admin, @cms_page] do |f| %>
  <%= render :partial => 'admin/shared/form_buttons' %>
  <%= f.error_messages %>

  <div class="input">
    <%= f.label :status, "Status#{required_tag}".html_safe, :class => 'title' %>
    <div class="field">
      <%= f.select :status, f.object.class::STATUSES %>
    </div>
  </div>
  <div class="input">
    <%= f.label :menu_title, 'Menu Title', :class => 'title' %>
    <div class="field"><%= f.text_field :menu_title %></div>
  </div>
<%=  f.fields_for :cms_meta do |builder| -%>
  <%= render 'admin/cms_metas/form_fields', :f => builder %>
<%   end -%>
<% end %>

app/views/admin/cms_pages/edit.html.erb
<h1><%= get_title %></h1>
<%= render 'form' %>

app/views/admin/cms_pages/index.html.erb
<h1>Pages</h1>
<ul class="top-nav"><li class="first last add-new"><%= link_to 'New Page', new_admin_cms_page_path, :title => 'Create New Page' %></li></ul>
<table class="list" cellpadding="0" cellspacing="0">
  <thead>
    <tr class="first last">
      <th class="first">Title</th>
      <%= render 'admin/cms_metas/shared_index_header' %>
      <th class="last">Status</th>
    </tr>
  </thead>
  <tbody>
<% @cms_pages.each do |cms_page| -%>
    <tr>
      <td class="first title">
        <div class="title">
          <%= link_to h(cms_page.cms_meta.title), edit_admin_cms_page_path(cms_page) %>
        </div>
        <div class="actions">
          <%= link_to 'Edit', edit_admin_cms_page_path(cms_page), :title => 'Edit Page' %>
          <%= link_to 'Destroy', [:admin, cms_page], :confirm => 'Are you sure?', :method => :delete, :class => 'last', :title => 'Delete Page' %>
        </div>
      </td>
      <%= render 'admin/cms_metas/shared_index_item', :cms_meta => cms_page.cms_meta %>
      <td class="last"><%= cms_page.status %></td>
    </tr>
<% end -%>
  </tbody>
</table>

app/views/admin/cms_pages/new.html.erb
<h1><%= get_title %></h1>
<%= render 'form' %>